'use strict';

/**
 * config/commandInfo.js — deskripsi singkat + alias tiap command bot.
 *
 * Dipakai halaman /command (controllers/commandController.js). Nggak dibaca
 * engine bot: nambah command baru TIDAK wajib nambah di sini — yang belum
 * ada deskripsinya cuma tampil tanpa keterangan, bukan hilang dari daftar.
 *
 * ALIAS di-generate dari grup `case` di plugins/ (fall-through yang badannya
 * nggak bercabang per-command). Skripnya: test/alias-command.js.
 */

const DESKRIPSI = {
  "absen": "Mulai absen",
  "accuweather": "Prakiraan cuaca beberapa hari",
  "aceh": "Kata mutiara bahasa Aceh",
  "add": "Tambah member ke grup pakai nomor",
  "addai": "Tambah bot AI ke grup",
  "addhp": "Tambah HP user",
  "addlevel": "Naikkan level user",
  "addlimit": "Tambah limit harian user",
  "addlist": "Tambah daftar",
  "addmoney": "Tambah uang user",
  "addprem": "Kasih akses premium ke user",
  "addpremgrup": "Kasih akses premium ke grup",
  "addrespon": "Tambah auto-respon",
  "addsewa": "Tambah masa sewa bot",
  "addxp": "Tambah XP user",
  "adventure": "Petualangan cari hadiah",
  "afk": "Pasang status AFK beserta alasannya",
  "aio": "Download dari hampir semua jenis link",
  "airdrop": "Ambil airdrop gratis",
  "antibot": "Hapus pesan yang dikirim dari bot WA Web",
  "artinama": "Cari arti nama kamu",
  "asahotak": "Kuis asah otak",
  "attp": "Teks jadi stiker bergerak",
  "autoacc": "Setujui permintaan join grup otomatis",
  "autoread": "Centang biru semua pesan otomatis",
  "backup": "Backup data bot",
  "bahan": "Lihat bahan yang kamu punya",
  "ban": "Ban user dari bot",
  "bandinghp": "Bandingin dua HP",
  "bank": "Simpan atau ambil uang di bank",
  "banmember": "Keluarkan member dan larang masuk lagi",
  "batak": "Kata mutiara bahasa Batak",
  "bcgc": "Broadcast ke semua grup",
  "bcgcht": "Broadcast ke semua chat pribadi",
  "bebaskan": "Bebaskan diri dari penjara",
  "beli": "Beli item dari toko",
  "berburu": "Berburu buat dapat bahan",
  "berita": "Berita terbaru",
  "bertarung": "Tarung lawan member lain",
  "bijak": "Kata-kata bijak",
  "block": "Blokir nomor di WhatsApp",
  "brat": "Teks gaya cover album brat",
  "bratvid": "Versi video dari brat",
  "broadcast": "Kirim pesan ke semua chat",
  "bypass": "Bypass shortlink",
  "bypasssfl": "Bypass shortlink sfile",
  "carifitur": "Cari command berdasarkan kata kunci",
  "catatan": "Daftar variabel yang bisa dipakai di teks welcome/left",
  "cekabsen": "Lihat siapa saja yang sudah absen",
  "cekasalmember": "Cek member yang nomornya sudah tidak aktif",
  "cekgiveaway": "Lihat peserta giveaway",
  "cekmenang": "Cek apakah kamu menang giveaway",
  "cekprofil": "Lihat profil RPG user",
  "cekroblox": "Cek akun Roblox",
  "ceksewa": "Cek sisa masa sewa",
  "checkwa": "Cek nomor itu terdaftar WhatsApp atau tidak",
  "chess": "Info akun Chess.com",
  "china": "Peribahasa China",
  "claim": "Ambil hadiah harian",
  "clearsession": "Hapus sesi bot, perlu scan ulang",
  "cleartmp": "Hapus file temporary",
  "close": "Tutup grup, cuma admin yang bisa kirim",
  "gcclose": "Samain dengan .close — tutup grup",
  "clue": "Minta petunjuk kuis yang sedang jalan",
  "coinflip": "Taruhan koin heads atau tails",
  "copet": "Copet uang orang",
  "craft": "Bikin item dari bahan yang terkumpul",
  "crm": "Panel CRM buat kelola data user",
  "cuaca": "Info cuaca satu kota",
  "dafont": "Cari font di dafont.com",
  "dafontdl": "Download font dari dafont.com",
  "dailymisi": "Ambil misi harian",
  "dare": "Tantangan random",
  "decode": "Baca teks yang di-encode base64",
  "decodeqr": "Baca isi QR code dari gambar",
  "delbye": "Hapus teks perpisahan yang sudah diset",
  "delete": "Hapus pesan yang kamu reply",
  "dellevel": "Turunkan level user",
  "dellimit": "Kurangi limit user",
  "delmoney": "Kurangi uang user",
  "delprem": "Cabut akses premium user",
  "delpremgrup": "Cabut akses premium grup",
  "delrespon": "Hapus auto-respon",
  "delsewa": "Hapus masa sewa",
  "delwarn": "Hapus riwayat peringatan",
  "delwelcome": "Hapus teks sambutan yang sudah diset",
  "delxp": "Kurangi XP user",
  "demote": "Cabut status admin member",
  "detect": "Notifikasi kalau ada perubahan di grup (nama, ikon, dll)",
  "didyoumean": "Saran command kalau kamu typo",
  "discord": "Info akun Discord",
  "document": "Kirim ulang dokumen sebagai file biasa",
  "drakor": "Info drakor",
  "dungeon": "Masuk dungeon cari hadiah",
  "duolingo": "Cek profil Duolingo",
  "encode": "Encode teks jadi base64",
  "facebook": "Download video Facebook",
  "fakecall": "Bikin gambar fake panggilan masuk",
  "fakecallip": "Bikin gambar fake panggilan pakai IP",
  "fakech": "Bikin gambar fake channel: nama, followers",
  "fakedana": "Bikin gambar fake saldo DANA",
  "fakegcios": "Bikin gambar fake grup GC",
  "fakemsg": "Owner react emoji tertentu, pesannya jadi promosi",
  "fakeovo": "Bikin gambar fake saldo OVO",
  "fakepptele": "Bikin gambar fake profil Telegram",
  "fakta": "Fakta unik random",
  "fancytext": "Ubah teks jadi gaya fancy",
  "fiersa": "Kutipan Fiersa Besari",
  "freefire": "Info akun Free Fire",
  "gacha": "Gacha item random",
  "gajian": "Ambil gaji dari pekerjaan kamu",
  "gcutama": "Tandai grup ini sebagai grup utama bot",
  "gdrive": "Download file dari Google Drive",
  "gempa": "Info gempa terbaru",
  "genius": "Cari lagu lewat Genius",
  "gcclose": "Tutup grup, cuma admin yang bisa kirim",
  "gcopen": "Buka grup supaya semua bisa kirim pesan",
  "genshin": "Info akun Genshin Impact",
  "getpp": "Ambil foto profil member (yang di-tag/di-reply)",
  "getppgc": "Ambil foto profil grup",
  "groupinfo": "Info grup: nama, jumlah member, deskripsi",
  "grupclose": "Atur jam grup ditutup otomatis",
  "grupopen": "Atur jam grup dibuka otomatis",
  "gcopen": "Samain dengan .open — buka grup",
  "timerchat": "Set timer pesan hilang (1d=1 detik, 30m=30 menit)",
  "gsmarena": "Cari spesifikasi HP di GSMArena",
  "hapusabsen": "Hapus sesi absen",
  "hapusgiveaway": "Batalkan giveaway",
  "hidetag": "Tag semua member tanpa tag-nya kelihatan",
  "hourly": "Ambil hadiah tiap jam",
  "httpheaders": "Lihat header HTTP sebuah website",
  "igqc": "Bikin gambar quote gaya Instagram",
  "igstoryimg": "Bikin gambar story Instagram",
  "ikut": "Ikut giveaway yang sedang jalan",
  "imei": "Cek info dari nomor IMEI",
  "info": "Info singkat bot: nama, platform, versi",
  "instagram": "Download media Instagram",
  "inventory": "Lihat barang di tas kamu",
  "iplookup": "Cari lokasi dari alamat IP",
  "iqc": "Bikin gambar quote",
  "jarak": "Hitung jarak antara dua tempat",
  "jawa": "Pepatah bahasa Jawa",
  "job": "Lihat pekerjaan kamu sekarang",
  "jodoh": "Cek kecocokan kamu sama orang lain",
  "kalendershalat": "Jadwal shalat satu bulan penuh",
  "kalkulator": "Hitung ekspresi matematika",
  "katabucin": "Kata-kata bucin",
  "katasore": "Kata-kata sore",
  "kbbi": "Cari arti kata di KBBI",
  "kebon": "Berkebun buat dapat bahan",
  "kerja": "Kerja buat dapat uang",
  "kick": "Keluarkan member dari grup",
  "kickall": "Keluarkan semua member dari grup",
  "koboy": "Kerja sampingan jadi koboy",
  "kodepos": "Cari kode pos suatu daerah",
  "konversitanggal": "Konversi tanggal Hijriah ke Masehi dan sebaliknya",
  "kuaishou": "Download video Kuaishou",
  "lamarkerja": "Lihat daftar pekerjaan yang tersedia",
  "leaderboard": "Papan peringkat pemain",
  "leaveall": "Suruh bot keluar dari semua grup",
  "leavegc": "Suruh bot keluar dari grup ini",
  "likee": "Download video Likee",
  "limit": "Sisa limit harian kamu",
  "link": "Ambil link undangan grup ini",
  "linkgc": "Ambil link undangan grup",
  "lirik": "Cari lirik lagu",
  "listadmin": "Daftar admin grup",
  "listafk": "Daftar member yang sedang AFK",
  "listblacklist": "Daftar nomor yang diblokir",
  "listblock": "Daftar nomor yang diblokir",
  "listgroup": "Daftar grup yang diikuti bot",
  "listmute": "Daftar grup yang dibisukan",
  "listprem": "Daftar user premium",
  "listrank": "Daftar rank user",
  "listrespon": "Daftar auto-respon",
  "listsewa": "Daftar semua sewa",
  "listtotalpesan": "Total pesan tiap member di grup",
  "listuser": "Daftar user bot",
  "listwarn": "Daftar member yang kena peringatan",
  "lk21": "Film trending di LK21",
  "lk21search": "Cari film di LK21",
  "maling": "Mencuri dari member lain",
  "mancing": "Mancing buat dapat ikan",
  "market": "Harga saham, crypto, forex, dan logam",
  "mcpedl": "Cari addon Minecraft",
  "me": "Lihat profil singkat kamu",
  "mediafire": "Download file dari MediaFire",
  "memory": "Pemakaian RAM server",
  "menu": "Daftar semua command, dikelompokkan per kategori",
  "minangkabau": "Kata mutiara Minangkabau",
  "minecraft": "Info akun Minecraft",
  "moddroid": "Download APK mod dari ModDroid",
  "money": "Lihat saldo uang kamu",
  "motivasi": "Kata motivasi",
  "mulaiabsen": "Mulai sesi absen dengan judul",
  "mulaigiveaway": "Mulai giveaway baru",
  "mute": "Bisukan bot di grup ini",
  "nationalday": "Hari besar apa hari ini",
  "ngeles": "Alasan ngeles buat nolak ajakan",
  "nik": "Baca info dari NIK KTP",
  "nimegami": "Anime trending di Nimegami",
  "nimegamis": "Cari anime di Nimegami",
  "npm": "Cek package di npm",
  "nyerah": "Menyerah dari kuis",
  "nyimak": "Bot diam total, tidak balas command",
  "ocr": "Baca teks dari gambar",
  "off": "Matikan fitur",
  "on": "Nyalakan fitur (tanpa argumen: lihat daftarnya)",
  "open": "Buka grup supaya semua bisa kirim pesan",
  "owner": "Kontak owner bot",
  "pakai": "Pakai item dari inventory",
  "pay": "Bikin QRIS buat bayar",
  "penjara": "Lihat daftar orang yang dipenjara",
  "pick": "Pilih satu acak dari beberapa opsi",
  "pindl": "Download media dari link Pinterest",
  "ping": "Cek bot masih hidup + kecepatan balas",
  "pinterest": "Cari gambar di Pinterest",
  "play": "Cari dan putar audio dari YouTube",
  "poll": "Bikin polling pilihan",
  "profile": "Lihat profil RPG kamu",
  "promote": "Jadikan member sebagai admin",
  "proteksi": "Lihat status semua fitur proteksi grup",
  "qrcode": "Bikin QR code dari teks atau link",
  "rampok": "Rampok uang member lain",
  "readmore": "Sisipkan pemisah baca selengkapnya",
  "reddit": "Download media dari Reddit",
  "rednote": "Download dari RedNote / Xiaohongshu",
  "removebg": "Hapus latar belakang gambar",
  "repair": "Perbaiki item yang rusak",
  "resep": "Cari resep masakan",
  "reset": "Reset data user",
  "resetlimit": "Reset limit user",
  "resetprofil": "Reset profil RPG user",
  "resetwarn": "Reset semua peringatan",
  "restart": "Restart bot",
  "restore": "Restore data bot dari backup",
  "reverseip": "Lihat domain yang ada di satu IP",
  "roblox": "Info akun Roblox",
  "rollgiveaway": "Undi pemenang giveaway",
  "rpg": "Nyalakan atau matikan sistem RPG di grup",
  "runtime": "Umur proses Node yang jalan",
  "rvo": "Buka ulang media sekali lihat",
  "searchcode": "Cari kode di GitHub",
  "setbio": "Ganti bio bot",
  "setbye": "Set teks ucapan member keluar",
  "setclose": "Set jam grup ditutup otomatis",
  "setdesc": "Ganti deskripsi grup",
  "setleft": "Set teks ucapan member keluar",
  "setlimitgc": "Set limit harian khusus grup ini",
  "setname": "Ganti nama member yang di-tag",
  "setnamegc": "Ganti nama grup",
  "setopen": "Set jam grup dibuka otomatis",
  "setpp": "Ganti foto profil bot",
  "setppgc": "Ganti foto profil grup",
  "setqris": "Set gambar QRIS buat pembayaran",
  "setsewa": "Atur masa sewa bot di grup ini",
  "setwarnlimit": "Set berapa kali di-warn sebelum member di-kick",
  "setwelcome": "Set teks sambutan member baru",
  "sfileco": "Download dari Sfile.co",
  "sfilemobi": "Download dari SfileMobi",
  "shalat": "Jadwal shalat satu kota",
  "shinigami": "Info anime di Shinigami",
  "sider": "Member paling banyak chat sejak bot nyala",
  "skill": "Naikkan skill kamu",
  "slot": "Main mesin slot",
  "soundcloud": "Download lagu dari SoundCloud",
  "spotify": "Cari lagu di Spotify",
  "spotifydl": "Download lagu Spotify",
  "spotifylyrics": "Cari lirik lagu dari Spotify",
  "ssweb": "Screenshot website",
  "stalkgithub": "Stalk profil GitHub",
  "stalktiktok": "Stalk profil TikTok",
  "steam": "Info game di Steam",
  "sticker": "Bikin stiker dari gambar atau video",
  "store": "Buka toko item RPG",
  "suitpvp": "Main suit lawan member lain",
  "swgc": "Kirim teks/media sebagai status grup (khusus admin grup/owner)",
  "tagadmin": "Tag semua admin grup",
  "tagall": "Tag semua member grup",
  "tagme": "Tag diri sendiri",
  "tambahsewa": "Tambah masa sewa dengan durasi",
  "tambang": "Menambang buat dapat bahan",
  "tebakanime": "Tebak judul anime",
  "tebakbendera": "Tebak negara dari benderanya",
  "tebakchara": "Tebak karakter",
  "tebakgambar": "Tebak gambar",
  "tebang": "Menebang pohon buat dapat kayu",
  "tgsticker": "Ambil sticker pack Telegram",
  "threads": "Download media dari Threads",
  "tictactoe": "Main tictactoe lawan member lain",
  "tiktok": "Download video TikTok",
  "tiktokphoto": "Cari foto TikTok",
  "todoc": "Convert jadi file dokumen",
  "tokopedia": "Cari produk di Tokopedia",
  "tomp4": "Convert stiker atau GIF jadi video",
  "topchat": "Ranking member paling aktif di grup",
  "topkoin": "Ranking pemain paling kaya",
  "topng": "Convert gambar jadi PNG",
  "totag": "Tag orang tertentu saja",
  "totalfitur": "Jumlah command yang tersedia",
  "tourl": "Upload gambar jadi link",
  "tourl2": "Upload file jadi link",
  "tovn": "Convert audio jadi voice note",
  "transfer": "Kirim uang ke member lain",
  "translate": "Terjemahkan teks ke bahasa lain",
  "ttqc": "Bikin gambar quote gaya TikTok",
  "ttsearch": "Cari video TikTok",
  "twitter": "Download video Twitter / X",
  "unban": "Cabut ban user",
  "unbanmember": "Cabut larangan masuk member",
  "unblock": "Buka blokir nomor",
  "unmute": "Nyalakan lagi bot di grup ini",
  "unreg": "Hapus akun RPG kamu",
  "unwarn": "Cabut peringatan member",
  "updatelist": "Ubah daftar",
  "uprespon": "Ubah auto-respon",
  "upscale": "Perbesar dan pertajam gambar",
  "uptime": "Berapa lama bot sudah nyala",
  "uptname": "Lama bot nyala beserta namanya",
  "warn": "Kasih peringatan ke member",
  "weekly": "Ambil hadiah mingguan",
  "wilayah": "Info wilayah dari kode pos",
  "wm": "Bikin stiker dengan watermark nama pack",
  "youtube": "Download video YouTube",
};

const ALIAS = {
  "accuweather": ["prakiraan"],
  "aceh": ["kataaceh"],
  "antibot": ["antidelete", "antilink", "antilinkv2", "antispam", "antisticker", "antitagsw", "antitoxic", "autosticker", "viewonce"],
  "bandinghp": ["comparehp"],
  "bank": ["atm"],
  "batak": ["katabatak"],
  "berburu": ["hunt"],
  "bertarung": ["fight"],
  "bypasssfl": ["bpsfl"],
  "cekroblox": ["stalkroblox"],
  "checkwa": ["cekwa"],
  "chess": ["stalkchess"],
  "china": ["katachina"],
  "coinflip": ["cf"],
  "crm": ["crm2"],
  "cuaca": ["weather"],
  "dare": ["tantangan"],
  "decodeqr": ["readqr"],
  "discord": ["stalkdiscord"],
  "facebook": ["fb", "fbdl"],
  "fakta": ["faktaunik"],
  "fancytext": ["fancy"],
  "fiersa": ["fiersabesari"],
  "freefire": ["ff", "stalkff"],
  "gdrive": ["gdrivedl"],
  "genshin": ["stalkgenshin"],
  "getpp": ["pp"],
  "getppgc": ["ppgc", "ppgroup"],
  "groupinfo": ["infogc"],
  "gsmarena": ["spek"],
  "hidetag": ["h"],
  "httpheaders": ["headers"],
  "imei": ["cekimei"],
  "instagram": ["ig", "igdl"],
  "iplookup": ["ipcek"],
  "jawa": ["katajawa", "pepatahjawa"],
  "kalendershalat": ["kshalat"],
  "katabucin": ["bucin"],
  "katasore": ["sore"],
  "konversitanggal": ["tanggal"],
  "kuaishou": ["kuaishoudl", "kwai"],
  "leaderboard": ["lb"],
  "likee": ["likeedl"],
  "listgroup": ["listgc"],
  "lk21": ["lk21trending"],
  "lk21search": ["filmsearch"],
  "market": ["crypto", "emas", "forex", "gold", "koin", "kurs", "saham", "silver", "xau"],
  "mediafire": ["mfdl"],
  "minangkabau": ["kataminang", "minang"],
  "minecraft": ["mc", "stalkmc"],
  "moddroid": ["moddroiddl"],
  "motivasi": ["katamotivasi"],
  "nationalday": ["hariini"],
  "ngeles": ["alasan"],
  "nik": ["nikinfo"],
  "nimegamis": ["animesearch"],
  "pinterest": ["pin"],
  "profile": ["me"],
  "qrcode": ["qr"],
  "reddit": ["redditdl"],
  "rednote": ["xhs", "xiaohongshu"],
  "removebg": ["rbg"],
  "rvo": ["readviewonce", "readvo"],
  "sfilemobi": ["sfile"],
  "shalat": ["jadwalshalat"],
  "soundcloud": ["scdl"],
  "spotifylyrics": ["slyrics"],
  "ssweb": ["screenshot", "ss"],
  "stalkgithub": ["ghstalk"],
  "stalktiktok": ["stalktt", "tiktokstalk"],
  "sticker": ["s"],
  "swgc": ["upswgc"],
  "tgsticker": ["stele", "telesticker"],
  "threads": ["threadsdl"],
  "tictactoe": ["ttt"],
  "tiktok": ["tiktokdl", "tt", "ttdl"],
  "tiktokphoto": ["ttkphoto"],
  "tokopedia": ["toped"],
  "tourl": ["upload"],
  "tourl2": ["upload2"],
  "tovn": ["2vo"],
  "transfer": ["tf"],
  "translate": ["terjemah", "tr"],
  "twitter": ["twit", "xdl"],
  "upscale": ["enhance", "hd"],
  "wilayah": ["cariwilayah"],
  "youtube": ["yt", "ytdl"],
};

module.exports = { DESKRIPSI, ALIAS };
